api:
  service:
    type: ClusterIP
    nodePort: 32208
  Image:
    Name: kuberlab/audience
    Tag: latest
  db:
    user: postgres
    password: postgres
  dns:
    - audience.kibernetika.io
  authKey: random-auth-key
  authAllowPublic: false
  baseUrl: https://audience.kibernetika.io
  dealer:
    enabled: false
    host: dev.kibernetika.io
    apiPath: /api/v0.2
    inferenceWorkspace: infws
    inferenceName: infname
    inferenceVersion: infversion
    servingWorkspace: srvws
    servingName: srvname
    servingToken: ZZZ
    storageEndpoint: https://storage.googleapis.com
    storageId: XXX
    storageSecret: YYY
    storageRegion: us-west-2
    storageBucket: kibernetika-audience
  storeVideoFiles: "true"
  servingRegisterToken: XXX

ui:
  Image:
    Name: kuberlab/audience-ui
    Tag: latest

render:
  Image:
    Name: kuberlab/audience-render
    Tag: latest

persistence:
  apiUpload:
    storageClass: nfs
    size: 10G
  apiVideo:
    storageClass: nfs
    size: 30G
  db:
    storageClass: nfs
    size: 5G
  images:
    storageClass: nfs
    size: 5G

ingress:
  tls:
    enabled: true

openness:
  enabled: false