api:
  Image:
    Name: kuberlab/audience
    Tag: latest
  db:
    user: postgres
    password: postgres
  dns:
    - audience.kibernetika.io
  authKey: random-auth-key
  baseUrl: https://audience.kibernetika.io
  dealer:
    host: dev.kibernetika.io
    apiPath: /api/v0.2
    inferenceWorkspace: infws
    inferenceName: infname
    inferenceVersion: infversion
    storageEndpoint: https://storage.googleapis.com
    storageId: XXX
    storageSecret: YYY
    storageRegion: us-west-2
    storageBucket: kibernetika-audience

ui:
  Image:
    Name: kuberlab/audience-ui
    Tag: latest

persistence:
  db:
    storageClass: nfs
    size: 5G
  images:
    storageClass: nfs
    size: 5G
