apiVersion: v1
kind: Service
metadata:
  labels:
    app: audience
    component: audience-api
  name: audience-api
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8088
  selector:
    app: audience
    component: audience-api
