apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: audience-api
spec:
  template:
    metadata:
      labels:
        app: audience
        component: audience-api
    spec:
      containers:
        - name:  audience-api
          image: "{{ printf "%s:%s" .Values.api.Image.Name .Values.api.Image.Tag}}"
          readinessProbe:
            httpGet:
              path: /probe
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: PG_HOST
              value: audience-db
            - name: PG_USER
              value: {{ .Values.api.db.user }}
            - name: PG_PWD
              value: {{ .Values.api.db.password }}
            - name: BASE_URL
              value: {{ .Values.api.baseUrl }}
            {{- if .Values.api.authKey }}
            - name: AUTH_KEY
              value: {{ .Values.api.authKey }}
            {{- end }}
            {{- if .Values.api.dealer.host }}
            - name: DEALER_HOST
              value: {{ .Values.api.dealer.host }}
            {{- end }}
            {{- if .Values.api.dealer.apiPath }}
            - name: DEALER_API_PATH
              value: {{ .Values.api.dealer.apiPath }}
            {{- end }}
            {{- if .Values.api.dealer.disableHttps }}
            - name: DEALER_DISABLE_HTTPS
              value: {{ .Values.api.dealer.disableHttps }}
            {{- end }}
            {{- if .Values.api.dealer.organization }}
            - name: ORGANIZATION_NAME
              value: {{ .Values.api.dealer.organization }}
            {{- end }}
            {{- if .Values.api.dealer.readAccessToken }}
            - name: ACCESS_TOKEN
              value: {{ .Values.api.dealer.readAccessToken }}
            {{- end }}
            {{- if .Values.api.dealer.writeAccessToken }}
            - name: MANAGE_TOKEN
              value: {{ .Values.api.dealer.writeAccessToken }}
            {{- end }}
          ports:
            - containerPort: 8088
              name: http
