apiVersion: v1
kind: Service
metadata:
  labels:
    app: audience
    component: audience-db
  name: audience-db
spec:
  ports:
    - name: psql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: audience
    component: audience-db
