apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audience-tls
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: kibernetika-cert-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- range $i, $dns := .Values.api.dns }}
      - "{{ $dns }}"
      {{- end }}
      secretName: audience-tls
  {{- end }}
  rules:
  {{- range $i, $dns := .Values.api.dns }}
  - host: {{ $dns }}
    http:
      paths:
        - path: /swagger
          pathType: Prefix
          backend:
            service:
              name: audience-api
              port:
                number: 8088
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: audience-api
              port:
                number: 8088
        - path: /images
          pathType: Prefix
          backend:
            service:
              name: audience-api
              port:
                number: 8088
        - path: /
          pathType: Prefix
          backend:
            service:
              name: audience-ui
              port:
                number: 80
    {{- end }}
