apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: audience-tls
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: kibernetika-cert-issuer
spec:
  tls:
    - hosts:
      {{- range $i, $dns := .Values.api.dns }}
      - "{{ $dns }}"
      {{- end }}
      secretName: audience-tls
  rules:
  {{- range $i, $dns := .Values.api.dns }}
  - host: {{ $dns }}
    http:
      paths:
        - path: /
          backend:
            serviceName: audience-api
            servicePort: 80
    {{- end }}
