apiVersion: v1
kind: Service
metadata:
  labels:
    app: audience
    component: audience-ui
  name: audience-ui
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: audience
    component: audience-ui
